[package]
name = "json_schema_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
serde.workspace = true
serde_json.workspace = true
json_schema = { path = "../json_schema" }
